# Generated by Django 5.0.10 on 2026-07-04 12:44

import django.db.models.deletion
import django.utils.timezone
import megaone.users.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTableOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeBasedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offer_banners/')),
                ('background_color', models.CharField(default='#f59e0b', max_length=20)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='offer_popups/')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this offer has been applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', megaone.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HeldCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField()),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('invoice_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_timezone', models.CharField(default='UTC', max_length=100)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='invoice_qrcodes/')),
                ('is_loyalty_payment', models.BooleanField(default=False, help_text='Paid using loyalty points')),
                ('loyalty_points_used', models.IntegerField(default=0, help_text='Loyalty points used for payment')),
                ('loyalty_points_earned', models.IntegerField(default=0, help_text='Loyalty points earned from this order')),
                ('loyalty_points_processed', models.BooleanField(default=False, help_text='Prevent duplicate point processing')),
                ('qr_offer_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='QR Table Offer discount %', max_digits=5)),
                ('qr_offer_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='QR Table Offer discount amount', max_digits=10)),
                ('deal_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="Today's Deal discount amount", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('used_points', models.IntegerField(default=0)),
                ('remaining_points', models.IntegerField(default=0)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='loyalty_qr/')),
                ('card_pdf', models.FileField(blank=True, null=True, upload_to='loyalty_cards/pdf/')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='loyalty_cards/images/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('first_card_popup_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_cards_loyaltycard',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('earned_points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('remaining_balance', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.loyaltycard')),
            ],
            options={
                'db_table': 'loyalty_cards_loyaltytransaction',
            },
        ),
        migrations.CreateModel(
            name='OperatorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_invoice', models.BooleanField(default=False)),
                ('can_edit_invoice', models.BooleanField(default=False)),
                ('can_delete_invoice', models.BooleanField(default=False)),
                ('can_apply_discount', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_categories', models.BooleanField(default=False)),
                ('can_stock_adjustment', models.BooleanField(default=False)),
                ('can_manage_customers', models.BooleanField(default=False)),
                ('can_view_dashboard_analytics', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('can_print_invoice', models.BooleanField(default=False)),
                ('can_cancel_invoice', models.BooleanField(default=False)),
                ('can_stock_position', models.BooleanField(default=False)),
                ('can_returns', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Permission',
                'verbose_name_plural': 'Operator Permissions',
                'db_table': 'operator_permissions',
            },
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_queue', to='users.invoice')),
            ],
            options={
                'db_table': 'users_orderqueue',
            },
        ),
        migrations.CreateModel(
            name='OrderQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.orderqueue')),
            ],
            options={
                'db_table': 'users_orderqueueitem',
            },
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('invoice_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('loyalty_points_to_redeem', models.IntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special combo price for the deal', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for percentage-based deals', max_digits=5, null=True)),
                ('deal_image', models.ImageField(blank=True, null=True, upload_to='deal_images/')),
                ('deal_banner', models.ImageField(blank=True, null=True, upload_to='deal_banners/')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_deals', to='menu.food')),
                ('products', models.ManyToManyField(blank=True, related_name='deals', to='menu.food')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, help_text="Associated Today's Deal", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.todaydeal'),
        ),
    ]
