# Generated by Django 5.0.10 on 2026-07-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='users.invoice')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'return_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_item_id', models.IntegerField(blank=True, help_text='Original InvoiceItem ID', null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.returninvoice')),
            ],
            options={
                'db_table': 'return_invoice_items',
            },
        ),
    ]
