# Generated by Django 5.0.10 on 2026-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_return_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='return_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
