# Generated by Django 5.0.10 on 2026-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_return_invoice_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingapproval',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
