# Generated by Django 5.0.10 on 2026-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tax_default_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash received from customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Change due to customer', max_digits=10),
        ),
    ]
