# Generated by Django 5.0.10 on 2026-07-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_invoice_cash_received_invoice_change_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqueueitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderQueue',
        ),
        migrations.DeleteModel(
            name='OrderQueueItem',
        ),
    ]
