# Generated by Django 5.0.10

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_orderqueueitem_order_delete_orderqueue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wholesale_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='wholesale_qrcodes/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wholesale_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.wholesalecustomer')),
            ],
            options={
                'db_table': 'wholesale_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.wholesaleinvoice')),
            ],
            options={
                'db_table': 'wholesale_invoice_items',
            },
        ),
    ]
