# Generated by Django 5.0.10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_wholesale_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalecustomer',
            name='total_deposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='total_redeemed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit made during this checkout', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='redeemed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount redeemed from account during this checkout', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Account balance before this transaction', max_digits=12),
        ),
        migrations.CreateModel(
            name='WholesaleAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('redeem', 'Redeem'), ('payment', 'Payment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='users.wholesalecustomer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='users.wholesaleinvoice')),
            ],
            options={
                'db_table': 'wholesale_account_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
