# Generated by Django 5.0.10 on 2026-07-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_wholesale_account_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleaccounttransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_account_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('frozen', 'Frozen')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='wholesaleaccounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('redeem', 'Redeem'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
