# Generated by Django 5.0.10 on 2026-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_wholesale_account_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoiceitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
