# Generated by Django 5.0.10 on 2026-07-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_wholesaleinvoiceitem_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='invoice_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='wholesale_original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='users.wholesaleinvoice'),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='users.invoice'),
        ),
    ]
