# Generated by Django 5.0.10 on 2026-07-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_returninvoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='can_create_wholesale_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_delete_wholesale_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_edit_wholesale_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_export_wholesale_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_view_wholesale_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WholesaleDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_payment', 'Mobile Payment'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('deposit_date', models.DateTimeField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reverse_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_deposits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='users.wholesalecustomer')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_wholesale_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesale Deposit',
                'verbose_name_plural': 'Wholesale Deposits',
                'db_table': 'wholesale_deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
