# Generated by Django 5.0.10 on 2026-07-14 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_operatorpermission_can_create_wholesale_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_create_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_delete_expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_edit_expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_manage_expense_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_view_expense_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_view_expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('expense_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_expenses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.expensecategory')),
            ],
            options={
                'verbose_name': 'Business Expense',
                'verbose_name_plural': 'Business Expenses',
                'db_table': 'business_expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='users.businessexpense'),
        ),
    ]
