# Generated by Django 5.0.10 on 2026-07-14 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_expensecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='can_manage_wholesale_credit',
            field=models.BooleanField(default=False, help_text='Can manage credit settlements and adjustments'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_view_wholesale_credit_reports',
            field=models.BooleanField(default=False, help_text='Can view wholesale credit reports'),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='used_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total credit amount currently used across invoices', max_digits=12),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount covered by credit', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Expected payment due date for credit invoices', null=True),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount actually paid (cash + redeem + deposit)', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial Paid'), ('credit_due', 'Credit Due'), ('overdue', 'Overdue'), ('returned', 'Returned')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='remaining_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding amount still due', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wholesaleaccounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('redeem', 'Redeem'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('credit', 'Credit Usage'), ('credit_settlement', 'Credit Settlement')], max_length=20),
        ),
        migrations.CreateModel(
            name='WholesaleCreditSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_credit_settlements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_settlements', to='users.wholesalecustomer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_settlements', to='users.wholesaleinvoice')),
            ],
            options={
                'db_table': 'wholesale_credit_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
