# Generated by Django 5.0.10 on 2026-07-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_operatorpermission_can_manage_wholesale_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='can_access_settings',
            field=models.BooleanField(default=False, help_text='Can access system settings (admin level)'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='can_manage_company',
            field=models.BooleanField(default=False, help_text='Can manage company profile and branding (admin level)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_creation', 'User Creation'), ('user_deactivation', 'User Deactivation'), ('user_activation', 'User Activation'), ('permission_change', 'Permission Change'), ('company_update', 'Company Information Update'), ('logo_change', 'Logo Change'), ('settings_change', 'System Settings Change'), ('password_reset', 'Password Reset')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_phone', models.CharField(blank=True, default='', max_length=50)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_website', models.URLField(blank=True, default='')),
                ('tax_label', models.CharField(default='GST', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('invoice_footer_text', models.TextField(blank=True, default='')),
                ('receipt_prefix', models.CharField(default='RCP-', max_length=20)),
                ('receipt_footer_text', models.TextField(blank=True, default='')),
                ('default_payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
