# Generated by Django 5.0.10 on 2026-07-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_system_setting_audit_log_admin_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_software_owner',
            field=models.BooleanField(default=False),
        ),
    ]
