# Generated by Django 5.0.10 on 2026-07-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_is_software_owner_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Company', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_number', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('tax_label', models.CharField(default='GST', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('invoice_footer_text', models.TextField(blank=True, default='')),
                ('receipt_prefix', models.CharField(default='RCP-', max_length=20)),
                ('receipt_footer_text', models.TextField(blank=True, default='')),
                ('default_payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('user_limit', models.PositiveIntegerField(default=10)),
                ('branch_limit', models.PositiveIntegerField(default=1)),
                ('product_limit', models.PositiveIntegerField(default=1000)),
                ('storage_limit', models.PositiveIntegerField(default=100, help_text='MB')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.company'),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('pos', 'POS'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('inventory', 'Inventory'), ('customers', 'Loyalty Cards'), ('suppliers', 'Suppliers'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('profit_loss', 'Profit & Loss'), ('credit_management', 'Credit Management')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='users.company')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'db_table': 'module_permissions',
                'unique_together': {('company', 'module_code')},
            },
        ),
    ]
