# Generated by Django 5.0.10 on 2026-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_company_systemsetting_company_user_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='company_name',
            field=models.CharField(default='POS', max_length=255),
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
