# Generated by Django 5.0.10 on 2026-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_company_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Module codes enabled for the business'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='superuser_created',
            field=models.BooleanField(default=False, help_text='Whether the first business superuser has been created'),
        ),
    ]
