# Generated by Django 5.0.10 on 2026-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_systemsetting_enabled_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='can_access_wholesale',
            field=models.BooleanField(default=False, help_text='Can access wholesale POS and management'),
        ),
    ]
