# Generated by Django 5.0.10 on 2026-07-16 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_food_wholesale_fields'),
        ('users', '0023_invoiceitem_unit_cost_at_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_stock', 'Opening Stock'), ('stock_adjustment', 'Stock Adjustment'), ('retail_sale', 'Retail Sale'), ('wholesale_sale', 'Wholesale Sale'), ('retail_return', 'Retail Return'), ('wholesale_return', 'Wholesale Return')], max_length=30)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice/Return number', max_length=100, null=True)),
                ('quantity_change', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='menu.food')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
