# Generated by Django 5.0.10 on 2026-07-16 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_inventory_fields'),
        ('users', '0024_stock_movement_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(help_text='Original purchase quantity')),
                ('remaining_quantity', models.PositiveIntegerField(help_text='Quantity still in stock')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit for this batch', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost of this batch', max_digits=12)),
                ('supplier', models.CharField(blank=True, help_text='Supplier name', max_length=255, null=True)),
                ('purchase_reference', models.CharField(blank=True, help_text='Purchase order / reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='menu.food')),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
                'db_table': 'inventory_batches',
                'ordering': ['purchase_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_costs', to='users.inventorybatch')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_costs', to='users.invoiceitem')),
                ('wholesale_invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_costs', to='users.wholesaleinvoiceitem')),
            ],
            options={
                'verbose_name': 'Sale Item Cost',
                'verbose_name_plural': 'Sale Item Costs',
                'db_table': 'sale_item_costs',
            },
        ),
    ]
