# Generated by Django 5.0.10 on 2026-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_inventory_batch_and_cost_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='total_returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount returned against this invoice', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='total_returned_qty',
            field=models.IntegerField(default=0, help_text='Total quantity returned against this invoice'),
        ),
    ]
