# Generated by Django 5.0.10 on 2026-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_wholesale_return_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price at time of purchase', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price at time of purchase', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('opening_stock', 'Opening Stock'), ('stock_adjustment', 'Stock Adjustment'), ('retail_sale', 'Retail Sale'), ('wholesale_sale', 'Wholesale Sale'), ('stock_purchase', 'Stock Purchase'), ('retail_return', 'Retail Return'), ('wholesale_return', 'Wholesale Return')], max_length=30),
        ),
    ]
