# Generated by Django 5.0.10 on 2026-07-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_inventorybatch_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingapproval',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to='users.invoice'),
        ),
    ]
