# Generated by Django 5.0.10 on 2026-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_invoice_fk_pending_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='heldcart',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendingapproval',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
