# Generated by Django 5.0.10 on 2026-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_add_customer_phone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
