# Generated by Django 5.0.10 on 2026-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_user_phone_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_theme_selection',
            field=models.BooleanField(default=True, help_text='Allow users to switch themes'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dark_mode_enabled',
            field=models.BooleanField(default=True, help_text='Enable dark mode availability'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_theme',
            field=models.CharField(default='user_choice', help_text='light, dark, or user_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(blank=True, default='', help_text='User theme preference: light, dark, or empty for system default', max_length=10),
        ),
    ]
