# Generated by Django 5.2.4 on 2026-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_systemsetting_allow_theme_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_drop',
            field=models.BooleanField(default=False, help_text='Can record cash drops'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_in',
            field=models.BooleanField(default=False, help_text='Can add cash to drawer'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_out',
            field=models.BooleanField(default=False, help_text='Can remove cash from drawer'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_override',
            field=models.BooleanField(default=False, help_text='Can override cash handling limits'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_refund_approve',
            field=models.BooleanField(default=False, help_text='Can approve cash refunds'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_report_view',
            field=models.BooleanField(default=False, help_text='Can view cash handling reports'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_close',
            field=models.BooleanField(default=False, help_text='Can close a cash drawer session'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_open',
            field=models.BooleanField(default=False, help_text='Can open a cash drawer session'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_void_approve',
            field=models.BooleanField(default=False, help_text='Can approve cash voids'),
        ),
    ]
