# Generated by Django 5.2.4 on 2026-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_operatorpermission_cash_drop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_audit_logs',
            field=models.BooleanField(default=False, help_text='Can view cash audit logs'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_dashboard_view',
            field=models.BooleanField(default=False, help_text='Can view cash handling dashboard'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_denomination_count',
            field=models.BooleanField(default=False, help_text='Can count denominations'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_drawer_view',
            field=models.BooleanField(default=False, help_text='Can view cash drawers list'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_no_sale',
            field=models.BooleanField(default=False, help_text='Can perform no-sale operations'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_reconciliation',
            field=models.BooleanField(default=False, help_text='Can perform closing reconciliation'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_settings_manage',
            field=models.BooleanField(default=False, help_text='Can manage cash handling settings'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_transaction_view',
            field=models.BooleanField(default=False, help_text='Can view cash transactions'),
        ),
    ]
