# Generated by Django 5.2.4 on 2026-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_force_close',
            field=models.BooleanField(default=False, help_text="Can force close any user's cash drawer session (admin)"),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_reopen',
            field=models.BooleanField(default=False, help_text='Can reopen a closed cash drawer session (admin)'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_view',
            field=models.BooleanField(default=False, help_text='Can view own cash drawer session details'),
        ),
        migrations.AddField(
            model_name='operatorpermission',
            name='cash_session_view_all',
            field=models.BooleanField(default=False, help_text='Can view all cash drawer sessions across users (admin)'),
        ),
    ]
