# Generated by Django 5.2.4 on 2026-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_ensure_staff_cash_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(default='general', max_length=100)),
                ('key', models.CharField(blank=True, default='', max_length=50)),
                ('ctrl', models.BooleanField(default=False)),
                ('shift', models.BooleanField(default=False)),
                ('alt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyboard Shortcut',
                'verbose_name_plural': 'Keyboard Shortcuts',
                'db_table': 'keyboard_shortcuts',
                'ordering': ['category', 'label'],
            },
        ),
    ]
