# Generated by Django 5.2.4 on 2026-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_keyboardshortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoiceitem',
            name='original_item_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Original InvoiceItem ID', null=True),
        ),
    ]
