# Generated by Django 5.2.4 on 2026-07-23 09:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_drawer_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Drawer Session',
                'verbose_name_plural': 'Cash Drawer Sessions',
                'db_table': 'cash_drawer_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('drop', 'Cash Drop'), ('opening_balance', 'Opening Balance'), ('closing_balance', 'Closing Balance'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice/Return/Reference number', max_length=100, null=True)),
                ('reference_model', models.CharField(blank=True, help_text='Model name (Invoice, ReturnInvoice, etc.)', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='Model PK', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Only cash affects drawer', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, help_text='Prevent duplicate processing', max_length=100, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cash_handling.cashdrawersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'db_table': 'cash_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
