# Generated by Django 5.2.4 on 2026-07-23 09:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_handling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('drop', 'Cash Drop'), ('void_sale', 'Void Sale'), ('no_sale', 'No Sale'), ('opening_balance', 'Opening Balance'), ('closing_balance', 'Closing Balance'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='CashApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('refund', 'Refund Approval'), ('void', 'Void Approval'), ('override', 'Override Approval')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='cash_handling.cashdrawersession')),
            ],
            options={
                'verbose_name': 'Cash Approval',
                'verbose_name_plural': 'Cash Approvals',
                'db_table': 'cash_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DenominationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_value', models.DecimalField(decimal_places=2, help_text='Value of denomination (e.g. 1000, 500, 100, 50, 20, 10, 5, 1, 0.25)', max_digits=10)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of notes/coins of this denomination')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='denomination_value * count', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_counts', to='cash_handling.cashdrawersession')),
            ],
            options={
                'verbose_name': 'Denomination Count',
                'verbose_name_plural': 'Denomination Counts',
                'db_table': 'cash_denomination_counts',
                'ordering': ['-denomination_value'],
            },
        ),
        migrations.CreateModel(
            name='NoSaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_sale_transactions', to='cash_handling.cashdrawersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_sale_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'No Sale Transaction',
                'verbose_name_plural': 'No Sale Transactions',
                'db_table': 'cash_no_sale_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
