# Generated by Django 5.0.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale selling price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='wholesale_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='wholesale_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
