# Generated by Django 5.0.10 on 2026-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_food_wholesale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='costing_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('average', 'Average Cost (AVCO)')], default='fifo', help_text='Inventory costing method', max_length=10),
        ),
        migrations.AddField(
            model_name='food',
            name='current_average_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current weighted average cost (AVCO)', max_digits=10),
        ),
        migrations.AddField(
            model_name='food',
            name='default_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default cost for future purchases', max_digits=10),
        ),
    ]
