# Generated by Django 5.2.4 on 2026-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_inventory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
