# Generated by Django 5.2.4 on 2026-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_food_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No'),
        ),
        migrations.AddField(
            model_name='food',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
